POST 127.0.0.1:8000//run-feed-job


###
POST 127.0.0.1:8000/predict
Content-Type: application/json

{
  "use_catboost": false,
  "products": [
    {
      "id": "5410103000001",
      "name": "Умная лампочка Яндекса E14",
      "vendor": "Яндекс",
      "categoryId": 10103,
      "params": {
        "Тип лампы": "Светодиодная",
        "Энергосберегающая": "1",
        "Форма колбы": "Свеча",
        "Тип цоколя": "E14",
        "Мощность": "4.8",
        "Напряжение": "220",
        "Свет": "RGB",
        "IP": "40",
        "МинТемп": "2700"
      }
    },
    {
      "id": "5410103000002",
      "name": "Умная лампочка Яндекса E27",
      "vendor": "Яндекс",
      "categoryId": 10103,
      "params": {
        "Тип лампы": "Светодиодная",
        "Энергосберегающая": "1",
        "Форма колбы": "Цилиндрическая",
        "Тип цоколя": "E27",
        "Напряжение": "220",
        "Свет": "RGB",
        "IP": "40",
        "МинТемп": "1700"
      }
    },
    {
      "id": "5410103000003",
      "name": "Умная лампочка Яндекса GU10",
      "vendor": "Яндекс",
      "categoryId": 10103,
      "params": {
        "Тип лампы": "Светодиодная",
        "Энергосберегающая": "1",
        "Форма колбы": "Софит",
        "Тип цоколя": "GU10",
        "Мощность": "4.9",
        "Напряжение": "220",
        "Свет": "RGB",
        "IP": "40",
        "МинТемп": "2700"
      }
    }
  ]
}